/home/carrot666/.config/openbox/environment: line 8: export: `': not a valid identifier

(nitrogen:884): Gtk-WARNING **: 01:34:09.595: Unable to locate theme engine in module_path: "murrine",

(nitrogen:884): Gtk-WARNING **: 01:34:09.596: Unable to locate theme engine in module_path: "murrine",

(nitrogen:884): Gtk-WARNING **: 01:34:09.598: Unable to locate theme engine in module_path: "murrine",

(nitrogen:884): Gtk-WARNING **: 01:34:09.779: Unable to locate theme engine in module_path: "murrine",

(nitrogen:884): Gtk-WARNING **: 01:34:09.779: Unable to locate theme engine in module_path: "murrine",

(nitrogen:884): Gtk-WARNING **: 01:34:09.779: Unable to locate theme engine in module_path: "murrine",
conky: desktop window (3ad) is root window
conky: window type - desktop
conky: drawing to created window (0xc00001)
conky: drawing to double buffer
conky: forked to background, pid is 920

tint2: xRandr: Found crtc's: 8
[1;34mtint2: xRandr: Linking output Virtual1 with crtc 0, resolution 1920x1080, DPI 96[0m
tint2: xRandr: crtc 1 seems disabled
tint2: xRandr: crtc 2 seems disabled
tint2: xRandr: crtc 3 seems disabled
tint2: xRandr: crtc 4 seems disabled
tint2: xRandr: crtc 5 seems disabled
tint2: xRandr: crtc 6 seems disabled
tint2: xRandr: crtc 7 seems disabled
tint2: No XSETTINGS manager, tint2 uses config option 'launcher_icon_theme'.
tint2: Loading config file: /home/carrot666/.config/tint2/tint2rc
tint2: real transparency on... depth: 32
tint2: panel items: TS
tint2: Systray composited rendering on
tint2: nb monitors 1, nb monitors used 1, nb desktops 4
[1;34mtint2: panel 1 uses scale 1 [0m
tint2: Kernel uevent interface initialized...
tint2: systray window 16777233
[1;32mtint2: systray started[0m
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

(xfsettingsd:934): xfsettingsd-WARNING **: 01:34:11.636: Property "/Gdk/WindowScalingFactor" has an unsupported type "guint".

(xfsettingsd:934): GLib-CRITICAL **: 01:34:11.861: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:934): GLib-GObject-CRITICAL **: 01:34:11.862: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:934): GLib-GObject-CRITICAL **: 01:34:11.866: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
vmware-user: could not open /proc/fs/vmblock/dev

(ob-autostart:927): Gtk-WARNING **: 01:34:12.878: Unable to locate theme engine in module_path: "murrine",

(ob-autostart:927): Gtk-WARNING **: 01:34:12.878: Unable to locate theme engine in module_path: "murrine",

(ob-autostart:927): Gtk-WARNING **: 01:34:12.879: Unable to locate theme engine in module_path: "murrine",
[1;32madd_icon: 25165827 (pamac-tray), pid 940, visual 0x5569480961f0, colormap 25165826, depth 32, width 1, height 1[0m
[1;32madd_icon: 23068675 (NetworkManager Applet), pid 941, visual 0x5569480961f0, colormap 23068674, depth 32, width 1, height 1[0m
polybar|warn:  No monitor specified, using "Virtual1"
polybar|error: Disabling module "temperature" (reason: The file '/sys/class/thermal/thermal_zone0/temp' does not exist)
[1;31mtint2: systray: error code 9[0m
[1;31mtint2: systray: error code 9[0m
[1;31mtint2: systray: error code 9[0m
[1;31mtint2: systray: error code 9[0m
[1;33mtint2: remove_icon: 25165827 (pamac-tray)[0m
[1;32madd_icon: 25165835 (pamac-tray), pid 940, visual 0x5569480961f0, colormap 25165826, depth 32, width 1, height 1[0m

(pamac-tray:940): Gdk-CRITICAL **: 01:34:15.760: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(vmware-user:944): Gtk-WARNING **: 01:34:16.556: gtk_disable_setlocale() must be called before gtk_init()
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/blueman-applet", line 121, in <module>
    BluemanApplet()
  File "/usr/sbin/blueman-applet", line 63, in __init__
    self.Plugins.Load()
  File "/usr/lib/python3.7/site-packages/blueman/main/PluginManager.py", line 90, in Load
    __import__(self.module_path.__name__ + ".%s" % plugin, None, None, [])
  File "/usr/lib/python3.7/site-packages/blueman/plugins/applet/AuthAgent.py", line 9, in <module>
    import blueman.main.applet.BluezAgent as BluezAgent
  File "/usr/lib/python3.7/site-packages/blueman/main/applet/BluezAgent.py", line 23, in <module>
    from blueman.bluez.Agent import Agent, AgentMethod
  File "/usr/lib/python3.7/site-packages/blueman/bluez/Agent.py", line 48, in <module>
    class Agent(dbus.service.Object):
  File "/usr/lib/python3.7/site-packages/blueman/bluez/Agent.py", line 56, in Agent
    @AgentMethod
  File "/usr/lib/python3.7/site-packages/blueman/bluez/Agent.py", line 38, in AgentMethod
    if BlueZInterface.get_interface_version()[0] < 5:
  File "/usr/lib/python3.7/site-packages/blueman/bluez/BlueZInterface.py", line 16, in get_interface_version
    obj = dbus.SystemBus().get_object('org.bluez', '/')
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Transport/mms.so could not be loaded: libmms.so.0: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Container/cue.so could not be loaded: libcue.so.2: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/wavpack.so could not be loaded: libwavpack.so.1: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/madplug.so could not be loaded: libmpg123.so.0: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/sid.so could not be loaded: libsidplayfp.so.4: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/amidi-plug.so could not be loaded: libfluidsynth.so.1: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/General/lirc.so could not be loaded: liblirc_client.so.0: cannot open shared object file: No such file or directory

(audacious:2851): Gtk-WARNING **: 01:40:36.999: Unable to locate theme engine in module_path: "murrine",

(audacious:2851): Gtk-WARNING **: 01:40:36.999: Unable to locate theme engine in module_path: "murrine",

(audacious:2851): Gtk-WARNING **: 01:40:36.999: Unable to locate theme engine in module_path: "murrine",
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) not binded to anything.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 50 (Shift_L) not binded to anything.
clientwin_handle(): KeyRelease 133 (Super_L) not binded to anything.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 39 (s) ignored.
clientwin_handle(): KeyRelease 133 (Super_L) ignored.
mainwin_handle(): Detected mouse button release on main window, exiting.
mainwin_handle(): Detected mouse button release on main window, exiting.
clientwin_handle(): Quitting.
clientwin_handle(): Quitting.
clientwin_handle(): Quitting.
clientwin_handle(): Quitting.
mainwin_handle(): Detected mouse button release on main window, exiting.
clientwin_handle(): KeyRelease 39 (s) ignored.
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Transport/mms.so could not be loaded: libmms.so.0: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Container/cue.so could not be loaded: libcue.so.2: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/wavpack.so could not be loaded: libwavpack.so.1: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/madplug.so could not be loaded: libmpg123.so.0: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/sid.so could not be loaded: libsidplayfp.so.4: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/Input/amidi-plug.so could not be loaded: libfluidsynth.so.1: cannot open shared object file: No such file or directory
ERROR plugin-load.cc:72 [plugin_load]: /usr/lib/audacious/General/lirc.so could not be loaded: liblirc_client.so.0: cannot open shared object file: No such file or directory

(audacious:3445): Gtk-WARNING **: 01:42:44.367: Unable to locate theme engine in module_path: "murrine",

(audacious:3445): Gtk-WARNING **: 01:42:44.367: Unable to locate theme engine in module_path: "murrine",

(audacious:3445): Gtk-WARNING **: 01:42:44.368: Unable to locate theme engine in module_path: "murrine",
